{
 "title": "Nginx Access Logs",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain",
    "query": "SELECT  DISTINCT domain\nFROM    metrics.nginx_logs"
   },
   {
    "name": "bot",
    "query": "SELECT DISTINCT toString(bot)\nFROM metrics.nginx_logs\nWHERE domain = $domain"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_local) AS time,\r\n  count() AS requests\r\nFROM \"metrics\".\"nginx_logs\"\r\nWHERE ( time >= $__fromTime AND time <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY time\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Requests By HTTP Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_local) AS time,\r\n  toString(status) AS metric,\r\n  count() AS value\r\nFROM \"metrics\".\"nginx_logs\"\r\nWHERE ( time >= $__fromTime AND time <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY time, status\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Requests Stats By Date",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT  toString(toDate((intDiv(toUInt32(time_local), 86400) * 86400))) as date,\r\n        CASE\r\n            WHEN status = 200 THEN '200'\r\n            WHEN status = 404 THEN '404'\r\n            WHEN status = 400 THEN '400'\r\n            WHEN status = 301 THEN '301'\r\n            WHEN status >= 300 AND status < 400 THEN '3xx'\r\n            WHEN status >= 400 AND status < 500 THEN '4xx'\r\n            WHEN status >= 500 AND status < 600 THEN '5xx'\r\n            ELSE 'Other'\r\n        END AS status,\r\n        count(*) as c\r\nFROM    metrics.nginx_logs\r\nWHERE   ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n    AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY date, status\r\nORDER BY date DESC, status\r\n"
    }
   ]
  },
  {
   "title": "Errors By Date",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT toString(date),\r\n  `status`,\r\n  method,\r\n  url,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE   ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n    AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n    AND `status` NOT IN (200, 201, 301)\r\n    AND method != 'OPTIONS'\r\nGROUP BY date, status, method, url\r\nORDER BY date DESC, c DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain ) AND ( bot IN ($bot) )"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) / ($__toTime - $__fromTime) c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\nAND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n\r\n"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n  AND `status` NOT IN (200, 201, 301)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Failed Requests %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (SUM(`status` NOT IN (200, 201, 301)) / SUM(`status`)) * 100\r\nFROM metrics.nginx_logs \r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT remote_addr) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain ) AND ( bot IN ($bot) )"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(body_bytes_sent) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain ) AND ( bot IN ($bot) )"
    }
   ]
  },
  {
   "title": "This Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Visitors This Month",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toString(toDate(toStartOfDay(time_local))) AS Date,\r\n  COUNT(DISTINCT remote_addr) AS Visitors\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= toStartOfMonth($__fromTime) AND time_local <= $__toTime )\r\n-- ( time_local >= toStartOfMonth(current_timestamp()) AND time_local <= toLastDayOfMonth(current_timestamp()) )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Date\r\nORDER BY Date ASC\r\nLIMIT 31"
      }
     ]
    },
    {
     "title": "By Day",
     "type": "table",
     "gridPos": { "h": 35, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  formatDateTime(time_local, '%W') AS DayOfWeek,\r\n  formatDateTime(time_local, '%F') AS Date,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  COUNT() AS Requests,\r\n  (Requests / Visitors) AS RequestsPerVisit,\r\n  SUM(body_bytes_sent) AS Bandwidth,\r\n  (Bandwidth / Visitors) As BandwidthPerVisit\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= toStartOfMonth($__fromTime) AND time_local <= $__toTime )\r\n-- ( time_local >= toStartOfMonth(current_timestamp()) AND time_local <= toLastDayOfMonth(current_timestamp()) )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Date, DayOfWeek\r\nORDER BY Date ASC\r\nLIMIT 31"
      }
     ]
    }
   ]
  },
  {
   "title": "All Months",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toStartOfMonth(time_local) AS time,\r\n  count() AS Requests\r\nFROM \"metrics\".\"nginx_logs\"\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY time\r\nORDER BY time ASC"
      },
      {
       "rawSql": "SELECT\r\n  toStartOfMonth(time_local) AS time,\r\n  count(DISTINCT remote_addr) AS Visitors\r\nFROM \"metrics\".\"nginx_logs\"\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY time\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 35, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  formatDateTime(time_local, '%M %Y') AS Date,\r\n  formatDateTime(time_local, '%Y-%m') AS DateOrd,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  --COUNT(DISTINCT remote_addr) AS Visitors,\r\n  COUNT() AS Requests,\r\n  (Requests / Visitors) AS RequestsPerVisit,\r\n  SUM(body_bytes_sent) AS Bandwidth,\r\n  (Bandwidth / Visitors) As BandwidthPerVisit\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= toStartOfMonth($__fromTime) AND time_local <= $__toTime )\r\n-- ( time_local >= toStartOfMonth(current_timestamp()) AND time_local <= toLastDayOfMonth(current_timestamp()) )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Date, DateOrd\r\nORDER BY DateOrd ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "All Years",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toStartOfYear(time_local) AS year,\r\n  count() AS Requests\r\nFROM \"metrics\".\"nginx_logs\"\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY year\r\nORDER BY year ASC"
      },
      {
       "rawSql": "SELECT\r\n  toStartOfYear(time_local) AS year,\r\n  count(DISTINCT remote_addr) AS Visitors\r\nFROM \"metrics\".\"nginx_logs\"\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY year\r\nORDER BY year ASC"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  formatDateTime(time_local, '%Y') AS Date,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  COUNT() AS Requests,\r\n  (Requests / Visitors) AS RequestsPerVisit,\r\n  SUM(body_bytes_sent) AS Bandwidth,\r\n  (Bandwidth / Visitors) As BandwidthPerVisit\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= toStartOfMonth($__fromTime) AND time_local <= $__toTime )\r\n-- ( time_local >= toStartOfMonth(current_timestamp()) AND time_local <= toLastDayOfMonth(current_timestamp()) )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Date\r\nORDER BY Date ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "All Hours",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toHour(time_local) AS hour,\r\n  count() AS Requests\r\nFROM \"metrics\".\"nginx_logs\"\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY hour\r\nORDER BY hour ASC"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toHour(time_local) AS Date,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  COUNT() AS Requests,\r\n  (Requests / Visitors) AS RequestsPerVisit,\r\n  SUM(body_bytes_sent) AS Bandwidth,\r\n  (Bandwidth / Visitors) As BandwidthPerVisit\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= toStartOfMonth($__fromTime) AND time_local <= $__toTime )\r\n-- ( time_local >= toStartOfMonth(current_timestamp()) AND time_local <= toLastDayOfMonth(current_timestamp()) )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Date\r\nORDER BY Date ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeInterval(time_local) AS time,\r\n  user_agent_family AS metric,\r\n  COUNT(*) AS value\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\n  AND ( bot IN ($bot) )\r\n  --AND user_agent_family != 'Other'\r\nGROUP BY time, metric\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  user_agent_family as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  user_agent_family AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    },
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  CONCAT(user_agent_family, ' ', user_agent_major) as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  CONCAT(user_agent_family, ' ', user_agent_major) AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeInterval(time_local) AS time,\r\n  os_family AS metric,\r\n  COUNT(*) AS value\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\n  AND ( bot IN ($bot) )\r\n  --AND os_family != 'Other'\r\nGROUP BY time, metric\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  os_family as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  os_family AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    },
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  CONCAT(os_family, ' ', os_major) as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  CONCAT(os_family, ' ', os_major) AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Countries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeInterval(time_local) AS time,\r\n  country AS metric,\r\n  COUNT(*) AS value\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\n  AND ( bot IN ($bot) )\r\nGROUP BY time, metric\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  country as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  country AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  SUM(body_bytes_sent) As Bytes\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  remote_addr as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  remote_addr AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  SUM(body_bytes_sent) As Bytes\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    },
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  REPLACE(cutIPv6(IPv4ToIPv6(remote_addr), 0, 2), '::ffff:', '') AS Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  REPLACE(cutIPv6(IPv4ToIPv6(remote_addr), 0, 2), '::ffff:', '') AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  SUM(body_bytes_sent) As Bytes\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "File Types",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeInterval(time_local) AS time,\r\n  url_extension AS metric,\r\n  COUNT(*) AS value\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\n  AND ( bot IN ($bot) )\r\n  AND url_extension != ''\r\nGROUP BY time, metric\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  url_extension as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n  AND url_extension != ''\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  url_extension AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  SUM(body_bytes_sent) As Bytes,\r\n  SUM(body_bytes_sent) / COUNT(*) As AvgSize\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n  AND url_extension != ''\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "URLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  url as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  url AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  SUM(body_bytes_sent) As Bytes,\r\n  SUM(body_bytes_sent) / COUNT(*) As AvgSize\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Referrers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  referrer_domain as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n  AND referrer_domain != ''\r\n  AND referrer_domain != $domain\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  referrer_domain AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  SUM(body_bytes_sent) As Bytes\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n  AND referrer_domain != ''\r\n  AND referrer_domain != ${domain}\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toString(status) as Dimension,\r\n  COUNT(*) AS c\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY c DESC\r\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 16, "w": 17, "x": 7, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toString(status) AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  SUM(body_bytes_sent) As Bytes\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  url AS Dimension,\r\n  COUNT(*) AS Requests,\r\n  COUNT(DISTINCT remote_addr) AS Visitors,\r\n  SUM(body_bytes_sent) As Bytes\r\nFROM metrics.nginx_logs\r\nWHERE ( time_local >= $__fromTime AND time_local <= $__toTime )\r\n  AND ( domain = $domain )\r\nAND ( bot IN ($bot) )\r\n  AND status = 404\r\nGROUP BY Dimension\r\nORDER BY Requests DESC\r\nLIMIT 100"
      }
     ]
    }
   ]
  }
 ]
}